---
title: "Data Workshop"
author: "JF"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Hello World!

# Level 1

## Level 2 (Marina's Favorite)

### Level 3

#### Level 4

##### Level 5

**bold** *italic* ***bold + italic***

-   listing
-   things

[save us, link!](https://restorationfund.org)

```{r}
## CTRL + ALT + I to make chunk ##
2 + 2
```

```{r}
#| code-fold: true

# this code only shows up if you click on dropdown to open
2+2
```

```{r}
#| echo: false

# hides code, shows output
2+2
```

```{r}
#| include: false

# this code will run but hides both code + output
2+2
```

# Script Organization feat. Penguins

## About (pseudocode)
penguins! penguins! penguins! penguins! penguins! penguins! penguins! 

## Setup 
```{r}
# load libraries ---- 
library(tidyverse)
library(here)
library(janitor)
library(lubridate) 
library(gghighlight)
library(sysfonts)
library(showtext)

# read in data ----
messy_penguins <- read.csv(here("data", "raw", "messy_penguins.csv")) 
nesting <- read.csv(here("data", "raw", "nesting.csv"))
```

## Data Exploration 
```{r}
head(messy_penguins)

#how many penguin species
n_distinct(messy_penguins$Species) #3
unique(messy_penguins$Species) #"Adelie", "Gentoo", "Chinstrap"

#what islands
unique(messy_penguins$island) #case issues

#bill length
#range(clean_penguins$bill_length_mm, na.rm = TRUE) #-999, missing
#class(clean_penguins$bill_length_mm) #character

#dates weird
#head(clean_penguins) #formats weird 

#check duplicates
#get_dupes(clean_penguins) #could be intentional, could be duplicates
## worth checking duplicates with data collector, take notes, etc. ## 

```

## Data Cleaning 
```{r}
## [ ] NAs?
## [X] unexpected negative values (bill_length_mm)
## [X] case (capitalization, island)
## [X] inconsistent dates (observation_date)

clean_penguins <- messy_penguins %>% 
  clean_names() #standardize col names to lower snake case

## chose to mutate from clean w/ new column names ##

clean_penguins <- clean_penguins %>%   
  mutate(island = str_to_title(island)) %>%  #island > consistent case
  mutate(bill_length_mm = as.numeric(bill_length_mm)) %>%  #change to numeric, remove unexpected values
  mutate(bill_length_mm = case_when(bill_length_mm == -999. ~ NA, 
                                    .default = bill_length_mm)) %>%  #change -999 to NA 
  mutate(date = parse_date_time(observation_date,#mutate to check
                                orders = c("dmy", "ymd", "mdy",
                                           "ymd HMS"))) %>% #fix obsv date
  separate(col = date, 
           into = c("date", "time"), #warning accounting for lack of time, OK!
           sep = " ") %>% 
  mutate(date = as.Date(date)) %>% #change to class: date
  select(-c(time, observation_date)) %>%  #remove: time, original obsv date
  mutate(year = year(date), #create year column (####)
         month = month(date, label = TRUE, abbr = FALSE), #create month (LONG MONTH NAME)
         day = day(date), #create day column
         day_of_year = yday(date)) #create day of year column

## cleaning duplicates ## 
nrow(clean_penguins) #352 originally

clean_penguins <- clean_penguins %>% 
  distinct()

nrow(clean_penguins) #344 post cleanup 
## and check! ## 
head(clean_penguins)

## save data 
write.csv(clean_penguins, here("data", "processed", "penguins.csv"))
# share data post clean up 
```

## Data Visualization

```{r}
# Simple bar chart 
penguin_bar <- ggplot(clean_penguins %>% 
         mutate(species = fct_rev(fct_infreq(species)))) + #order bars by obsv
  geom_bar(aes(x = species)) +
  geom_text(aes(x = species, label = after_stat(count)), #after_stat = funky
            stat = "count", #also funky
            hjust = 2, #move label 
            color = "white", #label color
            size = 5) + #label size
  labs(title = "Penguin counts at Palmer Station LTER", 
       subtitle = "2007-2009",
       caption = "Data: Gorman et al. 2014 via {palmerpenguins}") +
  coord_flip() + #flip x and y axes; up to personal preference/audience 
  theme_minimal(base_size = 14) + #change universal font size -> larger
  theme(
    axis.title = element_blank(), #remove axes titles
    axis.text.x = element_blank(), #remove X axis units
    panel.grid = element_blank(), #remove bg lines
    plot.caption = element_text(face = "italic",
                                color = "darkgray",
                                size = rel(0.7)), #70% of 14 
    plot.title.position = "plot", #moved alignment of title 
    plot.title = element_text(face = "bold"),
    plot.margin = margin(20, 20, 20, 20) #adjust plot margins
    ) #COMPLETE! 

# ggsave(here("figs", "pen_bar.png"), 
#        penguin_bar, 
#        width = 6) #default units = in
## MASS COMMENT OUT --> CTRL + ALT + C 
```


```{r}
#penguin size scatterplot 
pen_scatter <- ggplot(clean_penguins,
       aes(x = bill_length_mm, 
           y = bill_depth_mm, 
           color = species)) +
  geom_point(aes(shape = species),
             size = 3, 
             alpha = 0.7) +
  #geom_smooth(method = "lm", #method -> linear model 
              #se = FALSE) + #no standard error bars
  geomtextpath::geom_labelsmooth(aes(label = species), 
    method = "lm", #linear model 
    size = 5,
    linewidth = 1) +
  scale_color_manual(values = c("#648FFF", "#DC267F", "#FFB000")) +
  labs(title = "Penguin bill dimensions",
       subtitle = "Bill length and depth for Adelie, Chinstrap, and Gentoo penguins at Palmer Station LTER",
       x = "Bill length (mm)",
       y = "Bill depth (mm)",
       color = "Penguin species", #legend
       shape = "Penguin species") + #legend
  theme_minimal(base_size = 14) +
  theme(
    plot.title.position = "plot", 
    plot.margin = margin(10,10,10,10),
    axis.title.x = element_text(margin = margin(15, 0, 0, 0)),
    axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
    plot.title = element_text(face = "bold"),
    legend.position = "none" 
  )
  
ggsave(here("figs", "pen_scatter.png"),
       pen_scatter, width = 12, height = 8)
```


